name: تشغيل السكريبت اليومي

on:
  schedule:
    - cron: '30 2 * * *'   # الوقت الذي تريده
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
      
        with:
          python-version: '3.x'
      - 
      run: python main.py   # تأكد أن اسم الملف مطابق



      
