name: تشغيل السكريبت اليومي

on:
  schedule:
    - cron: '30 2 * * *'   # يمكنك تغيير الوقت هنا
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: تثبيت المكتبات
      run: pip install pandas
    - name: تشغيل الكود
      run: python main.py   # تأكد من اسم ملفك (هنا main.py)
